### ISSUE TITLE
Including files by pattern not working in .net 6

### ISSUE THREAD

**Issue by DeweyShuburte** [ligershark/WebOptimizer#204] opened 2021-11-30 19:43 UTC
Maybe I'm doing something wrong but I can no longer get file pattern to work after switching to .net 6.

example
"css/thirdparty/**/*.css"

If I add each file individually, it works fine.

**Comment by jdmeer** [comment] 2021-12-03 14:57
You can work around the bug using `UseContentRoot()` and adjusting your path accordingly.

`pipeline.AddCssBundle("/css/bundle.css", "wwwroot/css/thirdparty/**/*.css").UseContentRoot();`

**Comment by ajkonkol** [comment] 2021-12-09 00:50
Further investigation seems to reveal that the root cause is that in .NET 6, the `WebRootFileProvider `on `IWebHostEnvironment `is now a `CompositeFileProvider `with two underlying providers: a `Microsoft.AspNetCore.StaticWebAssets.ManifestStaticWebAssetFileProvider` and a `Microsoft.Extensions.FileProviders.PhysicalFileProvider`.  In .NET 5, the `WebRootFileProvider `is simply a `Microsoft.Extensions.FileProviders.PhysicalFileProvider`.
This seems to interfere with the ability to use file globbing.

**Comment by ajkonkol** [comment] 2021-12-10 01:37
I think this is fixed by this PR? #205

**Comment by ajkonkol** [comment] 2021-12-21 14:26
I have confirmed that this issue is fixed (at least for me) with the latest release from NuGet (3.0.344).

**Closed** 2021-12-22 18:07 UTC

**Comment by Acruval** [comment] 2022-01-03 23:47
Hello I am getting this problem in 3.1 too. (And in 6.01 of course. I create an app for each ### one.
the only diference in 3.1 I am not getting the v parameter
Just say even the page can work pipeline.AddCssBundle("/css/bundle.css", "css/site.css"); break the default minimize so at the moment I use just services.AddWebOptimizer(); Cheers

**Comment by EmilAlipiev** [comment] 2022-03-22 22:44
@ajkonkol does your solution work with scss to css also? I couldnt make both solutions working somehow. I have updated on the latest stable nuget version

**Comment by Acruval** [comment] 2022-10-11 08:41
Hi
 No I am not using scss
